using Azure.Storage.Blobs;
using DotNet.Testcontainers.Builders;
using System.Text;
using Testcontainers.Azurite;

namespace AzuriteUI.Web.IntegrationTests.Helpers;

/// <summary>
/// Fixture for Azurite integration tests.
/// </summary>
[ExcludeFromCodeCoverage(Justification = "Test fixture")]
public class AzuriteFixture : IAsyncLifetime
{
    /// <summary>
    /// Reference to the Docker container image for Azurite.
    /// </summary>
    public const string ContainerImage = "mcr.microsoft.com/azure-storage/azurite:latest";

    /// <summary>
    /// Reference to the internal container instance generated by TestContainers.
    /// </summary>
    private readonly AzuriteContainer _container;

    /// <summary>
    /// A lazy reference to the BlobServiceClient for interacting with Azurite.
    /// </summary>
    private readonly Lazy<BlobServiceClient> _client;

    /// <summary>
    /// Creates a new instance of the <see cref="AzuriteFixture"/>. 
    /// </summary>
    public AzuriteFixture()
    {
        _container = new AzuriteBuilder().WithImage(ContainerImage)
            .WithWaitStrategy(Wait.ForUnixContainer().UntilExternalTcpPortIsAvailable(10000))
            .Build();
        _client = new Lazy<BlobServiceClient>(CreateClient);
    }

    #region IAsyncLifetime Implementation
    /// <summary>
    /// Initializes the Azurite container and creates the BlobServiceClient.
    /// </summary>
    public async ValueTask InitializeAsync()
    {
        await _container.StartAsync();
    }

    /// <summary>
    /// Stops and disposes the Azurite container.
    /// </summary>
    public async ValueTask DisposeAsync()
    {
        await _container.StopAsync();
        await _container.DisposeAsync();
        GC.SuppressFinalize(this);
    }
    #endregion

    /// <summary>
    /// Retrieves the connection string for the Azurite instance.
    /// </summary>
    public string ConnectionString { get => _container.GetConnectionString(); }

    /// <summary>
    /// Retrieves the BlobServiceClient for interacting with the Azurite instance.
    /// </summary>
    public BlobServiceClient Client { get => _client.Value; }

    /// <summary>
    /// An internal method for creating the client to connect to Azurite.
    /// </summary>
    /// <returns>The <see cref="BlobServiceClient"/> instance.</returns>
    private BlobServiceClient CreateClient()
    {
        return new BlobServiceClient(ConnectionString);
    }

    /// <summary>
    /// Checks if a blob exists in the specified container.
    /// </summary>
    /// <param name="containerName">The container name</param>
    /// <param name="blobName">The blob name</param>
    /// <returns><c>true</c> if the blob exists; otherwise, <c>false</c>.</returns>
    public async Task<bool> BlobExistsAsync(string containerName, string blobName)
    {
        var containerClient = Client.GetBlobContainerClient(containerName);
        var blobClient = containerClient.GetBlobClient(blobName);
        var response = await blobClient.ExistsAsync();
        return response.Value;
    }

    /// <summary>
    /// Cleans up all containers and blobs in the Azurite instance.
    /// </summary>
    public async Task CleanupAsync()
    {
        List<string> containerNames = await Client.GetBlobContainersAsync().Select(c => c.Name).ToListAsync();
        try
        {
            foreach (var name in containerNames)
            {
                _ = await Client.DeleteBlobContainerAsync(name);
            }
        }
        catch
        {
            // Ignore cleanup errors.
        }
    }

    /// <summary>
    /// Helper method to upload a simple blob with text content and a specified content type.
    /// </summary>
    public async Task<string> CreateBlobAsync(string containerName, string blobName, string content, string contentType = "text/plain")
    {
        var containerClient = Client.GetBlobContainerClient(containerName);
        var blobClient = containerClient.GetBlobClient(blobName);

        var binaryData = new MemoryStream(Encoding.UTF8.GetBytes(content));
        var blobOptions = new Azure.Storage.Blobs.Models.BlobUploadOptions
        {
            HttpHeaders = new Azure.Storage.Blobs.Models.BlobHttpHeaders
            {
                ContentType = contentType
            }
        };
        await blobClient.UploadAsync(binaryData, blobOptions);
        return blobName;
    }

    /// <summary>
    /// Creates a new container in the Azurite instance.
    /// </summary>
    /// <param name="containerName">The name of the container.</param>
    /// <param name="metadata">Optional metadata for the container.</param>
    public async Task<string> CreateContainerAsync(string containerName, IDictionary<string, string>? metadata = null)
    {
        await Client.CreateBlobContainerAsync(containerName, metadata: metadata);
        return containerName;
    }
}