namespace AzuriteUI.Web.Services.CacheSync.Models;

/// <summary>
/// The potential events that can be generated by an IQueueManager.
/// </summary>
public enum QueueEvent
{
    /// <summary>
    /// Work was enqueued - the QueuedWork is not null.
    /// </summary>
    WorkEnqueued,

    /// <summary>
    /// Work on queued work was started - the QueuedWork is not null.
    /// </summary>
    WorkStarted,

    /// <summary>
    /// Work on the queued work finished successfully - the QueuedWork is not null.
    /// </summary>
    WorkFinished,

    /// <summary>
    /// An error occurred while processing the queued work - the QueuedWork and Exception are not null.
    /// </summary>
    WorkErrored,

    /// <summary>
    /// The queue was started (QueuedWork and Exception are null)
    /// </summary>
    QueueStarted,

    /// <summary>
    /// The queue was stopped (QueuedWork and Exception are null)
    /// </summary>
    QueueStopped
}
