namespace AzuriteUI.Web.Services.CacheSync.Models;

/// <summary>
/// The event arguments for an event generated by an IQueueManager.
/// </summary>
/// <param name="eventType">The type of event.</param>
/// <param name="queuedWork">The queued work item (optional).</param>
/// <param name="exception">The exception that occurred (optional).</param>
public class QueueManagerEventArgs(QueueEvent eventType, QueuedWork? queuedWork = null, Exception? exception = null) : EventArgs
{
    /// <summary>
    /// The event type.
    /// </summary>
    public QueueEvent EventType => eventType;

    /// <summary>
    /// The date and time that the event was created.
    /// </summary>
    public DateTimeOffset EventTime => DateTimeOffset.UtcNow;

    /// <summary>
    /// The queued work being processed.
    /// </summary>
    public QueuedWork? QueuedWork => queuedWork;

    /// <summary>
    /// The exception that was generated.
    /// </summary>
    public Exception? Exception => exception;
}